name: 'Run ESlint on changed files'
description: 'Run ESlint on changed files'
author: 'KaelenProctor'
inputs:
  config_path:
    description: 'CONFIG_PATH'
    required: true
  eslint_flags:
    description: 'ESLINT_FLAGS'
    required: true
  print_changed_files:
    description: 'PRINT_CHANGED_FILES'
    default: false
    required: true
runs:
  using: 'composite'
  steps:
    - run: .github/actions/eslint/script.sh
      shell: bash
      env:
        INPUT_CONFIG_PATH: ${{ inputs.config_path }}
        INPUT_ESLINT_FLAGS: ${{ inputs.eslint_flags }}
        INPUT_PRINT_CHANGED_FILES: ${{ inputs.print_changed_files }}
        # Pull request base SHA, or the SHA of the branch before push
        INPUT_BASE_SHA: ${{ github.event.pull_request.base.sha || github.event.before }}
        INPUT_BRANCH_SHA: ${{ github.sha }}
