name: CI Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Enable Corepack
        run: corepack enable
      - name: Setup
        run: npm ci
      - name: Check Code Style
        run: npm run lint
      - name: Run eslint on changed files
        uses: tj-actions/eslint-changed-files@v25
        with:
          config_path: 'eslint.config.mjs'
          extra_args: '--max-warnings=0'
      - name: Run Prettier on changed files
        uses: creyD/prettier_action@v4.3
        with:
          only_changed: true
          prettier_options: --max-warnings 0 **/*.{js,jsx,ts,tsx}
      - name: Build
        run: npm run ci-build
